### ISSUE TITLE
How can I change icon image?

### ISSUE THREAD

**Issue by JooMiHyun** [shbatm/MMM-OnScreenMenu#10]
I can't find changing button icon space.

**Comment by shbatm** [comment]
The icons for the menu are changed in the config file.  Are you trying to change the icon for the menu itself (the "hamburger" icon)?  There is no option to change this from the config, but you can change it if you edit `.../MagicMirror/modules/MMM-OnScreenMenu/MMM-OnScreenMenu.js` [line # 330](https://github.com/shbatm/MMM-OnScreenMenu/blob/master/MMM-OnScreenMenu.js#L330).  Change "fa-bars" to "fa-whatever".  

Icon Names are from https://fontawesome.com/icons
