### ISSUE TITLE
dont know how to use it...please help

### ISSUE THREAD

**Issue by alifsuria** [shbatm/MMM-OnScreenMenu#12]
I dont understand about this...can someone tell me about this and how to use it? 
![capt2ure](https://user-images.githubusercontent.com/35814118/46918066-b4b26380-cfff-11e8-92ae-f1a6ac7b8a1f.PNG)

**Comment by shbatm** [comment]
I can provide help, but please tell me about what you dont understand and what you are trying to do. Are you trying to control the menu from another module (which is the snippet you posted) or are you having a problem with the menu itself?

**Comment by alifsuria** [comment]
im new to MM and module...i want to use the menu to link to MMM-page selector..so when im want to the next page i want to click at the onscreen menu...so i thought the sendnotification can link it...can it use it like that?thanks for replying

**Comment by shbatm** [comment]
If I understand correctly, you want to use the menu to pick and switch to the different pages.

You can add menu items in the OnScreenMenu section of your your config file to switch to the different pages:

```js
menuItems: {
notify1: {  title: "Page One", 
            icon: "eye", 
            notification: "PAGE_SELECT", 
            payload: "PageName" },
notify2: {  title: "Page Two", 
            icon: "eye", 
            notification: "PAGE_SELECT", 
            payload: "Page2Name" },
}

```

Also, for general help like this, the forum is a better place to post. More people will see and be able to help. 
https://forum.magicmirror.builders
