### ISSUE TITLE
are the functionalities included or only the menu?

### ISSUE THREAD

**Issue by jadgsam** [shbatm/MMM-OnScreenMenu#2]
Hello,
When I included this module I see the new menu included but no function is triggered after pressing buttons. After checking code I do not realize the functions to reboot, shutdown and the others are included. Please confirm if I am right or not?

Thanks in advance

**Comment by shbatm** [comment]
These functions are included. They are server-side so they are in node_helper.js. 

Please post config section for help and check there are no errors on console (or pm2 logs if using pm2)

**Comment by jadgsam** [comment]
Thanks for your answer

Below you will see the config section as it was in the example:

       		{
            		module: 'MMM-OnScreenMenu',
            		position: 'bottom_right',
            		/* Valid positions: 'top_right', 'top_left', 'bottom_right', 'bottom_left' */
            		config: {
                		touchMode: true,
                		enableKeyboard: true,
                	// ... see more options below
            		}
        	}

From console now I see errors when trying to restart MagicMirror twice:

Ready to go! Please point your browser to: http://localhost:8080
Create new calendar fetcher for url: https://www.google.com/calendar/ical/psnmblmbogte9ohfhij0kjiebc%40group.calendar.google.com/public/basic.ics - Interval: 300000
Create new news fetcher for url: http://www.telam.com.ar/rss2/ultimasnoticias.xml - Interval: 300000
Restarting MagicMirror via pm2...
stderr: "[PM2][ERROR] Process mm not found
"
Restarting MagicMirror via pm2...
stderr: "[PM2][ERROR] Process mm not found
"
Restarting MagicMirror via pm2...
exec error: Error: Command failed: pm2 restart mm

**Comment by AffidavitDonda** [comment]
Hello,
There is a small error in the installation description:
`git clone https://github.com/shbatm/MMM-KeyBindings` must be replaced by
`git clone https://github.com/shbatm/MMM-OnScreenMenu`.

Thanks for the nice modules

**Comment by shbatm** [comment]
@jadgsam Please see the updated sample config section in the README, also as @AffidavitDonda pointed out, please make sure you clone the correct repo.

@AffidavitDonda thanks for pointing out the error!
