### ISSUE TITLE
OnScreenMenu is not showing up

### ISSUE THREAD

**Issue by jaxharkley** [shbatm/MMM-OnScreenMenu#5]
I made every step from the installing guide, and there's no error but when I open MagicMirror, the OnScreenMenu is not showing up. It just says "Loading...".
Here's the code I typed in the config.js file:

{
                     module: 'MMM-OnScreenMenu',
                             position: 'bottom_right',
                             /* Valid positions: 'top_right', 'top_left', 'bottom_right', 'bottom_left' */
                             config: {
                                 touchMode: false,
                                 
                                 menuItems: {
            
                                     monitorOff: { title: "Turn Off Monitor", icon: "television", source: "SERVER" },
                                     refresh: { title: "Refresh", icon: "recycle", source: "LOCAL" },
                                     restart: { title: "Restart MagicMirror", icon: "refresh", source: "ALL" },
                                     reboot: { title: "Reboot", icon: "spinner" },
                                     shutdown: { title: "Shutdown", icon: "power-off" }

                                },
                                enableKeyboard: true,
                            }  
                
                },

Please, can somebody help me to solve this, I would really like to use the OnScreenMenu in my MagicMirror. I also used the new URL to clone the module in the MagicMirror file.

**Comment by jaxharkley** [comment]
I solved the problem by myself. I didn't realise that it just shows when I move the mouse in the direction of it. But is there a way that it always shows and isn't hiding?

**Comment by jaxharkley** [comment]
Okay, found that out, too, by clicking on one of the buttons.

**Comment by shbatm** [comment]
@jaxharkley -- Glad you seem to have gotten it sorted out.  For clarity: setting the `touchMode: true,` setting will keep the button always visible on the screen.
